-- ============================================================
-- MIBOOKING — RIDERS TÉCNICOS (FASE 1)
--
-- Requisitos:
--   1. Núcleo multiusuario y datos por workspace.
--   2. Módulo Documentos/Contratos ya instalado.
--
-- Incluye:
--   * Configuración técnica por Formato.
--   * Riders versionados por cotización.
--   * Snapshot permanente del rider.
--   * PDF privado en Supabase Storage.
--   * Permisos para Artista y Gestor.
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 1. CONFIGURACIÓN TÉCNICA DEL FORMATO
-- ------------------------------------------------------------

alter table public.formatos
  add column if not exists rider_config jsonb not null default '{}'::jsonb;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'formatos_rider_config_object_check'
      and conrelid = 'public.formatos'::regclass
  ) then
    alter table public.formatos
      add constraint formatos_rider_config_object_check
      check (jsonb_typeof(rider_config) = 'object');
  end if;
end
$$;

comment on column public.formatos.rider_config is
  'Configuración técnica editable del Formato: integrantes, canales, monitores, backline, tarima, PA, electricidad y hospitalidad.';


-- ------------------------------------------------------------
-- 2. RIDERS GENERADOS
-- ------------------------------------------------------------

create table if not exists public.riders_tecnicos (
  id bigint generated by default as identity primary key,

  workspace_id bigint not null
    references public.workspaces(id)
    on delete restrict,

  cotizacion_id uuid not null
    references public.cotizaciones(id)
    on delete restrict,

  formato_id uuid
    references public.formatos(id)
    on delete set null,

  numero text not null,
  version integer not null default 1,
  estado text not null default 'Generado',

  datos_snapshot jsonb not null default '{}'::jsonb,

  pdf_path text,
  destinatario_email text,

  generado_por uuid not null
    references auth.users(id)
    on delete restrict,

  enviado_at timestamptz,
  confirmado_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint riders_tecnicos_numero_no_vacio
    check (length(trim(numero)) > 0),

  constraint riders_tecnicos_version_positiva
    check (version >= 1),

  constraint riders_tecnicos_estado_check
    check (
      estado in (
        'Generado',
        'Enviado',
        'Confirmado',
        'Cancelado',
        'Reemplazado'
      )
    ),

  constraint riders_tecnicos_cotizacion_version_unique
    unique (cotizacion_id, version),

  constraint riders_tecnicos_numero_unique
    unique (numero)
);

create index if not exists riders_tecnicos_workspace_idx
  on public.riders_tecnicos(workspace_id, created_at desc);

create index if not exists riders_tecnicos_cotizacion_idx
  on public.riders_tecnicos(cotizacion_id, version desc);

create index if not exists riders_tecnicos_formato_idx
  on public.riders_tecnicos(formato_id);

create index if not exists riders_tecnicos_estado_idx
  on public.riders_tecnicos(workspace_id, estado);


-- ------------------------------------------------------------
-- 3. PREPARAR Y VALIDAR CADA RIDER
-- ------------------------------------------------------------

create or replace function public.prepare_technical_rider_row()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_quote public.cotizaciones%rowtype;
  v_format public.formatos%rowtype;
  v_next_version integer;
  v_quote_number text;
begin
  if tg_op = 'UPDATE' then
    if new.workspace_id is distinct from old.workspace_id
       or new.cotizacion_id is distinct from old.cotizacion_id
       or new.formato_id is distinct from old.formato_id
       or new.version is distinct from old.version
       or new.numero is distinct from old.numero then
      raise exception
        'No se permite mover un rider ni modificar su número, versión, cotización o formato.';
    end if;

    new.updated_at := now();
    return new;
  end if;

  new.workspace_id :=
    public.resolve_user_workspace(new.workspace_id);

  select *
  into v_quote
  from public.cotizaciones c
  where c.id = new.cotizacion_id
    and c.workspace_id = new.workspace_id;

  if not found then
    raise exception
      'La cotización seleccionada no pertenece al Artista activo.';
  end if;

  if trim(coalesce(v_quote.estado, '')) not in (
    'Confirmada',
    'Aprobada'
  ) then
    raise exception
      'Solo se puede generar un rider desde una cotización Confirmada o Aprobada.';
  end if;

  if v_quote.formato_id is null then
    raise exception
      'La cotización no tiene un Formato asociado.';
  end if;

  if new.formato_id is null then
    new.formato_id := v_quote.formato_id;
  end if;

  if new.formato_id is distinct from v_quote.formato_id then
    raise exception
      'El Formato del rider no coincide con el Formato de la cotización.';
  end if;

  select *
  into v_format
  from public.formatos f
  where f.id = new.formato_id
    and f.workspace_id = new.workspace_id;

  if not found then
    raise exception
      'El Formato seleccionado no pertenece al Artista activo.';
  end if;

  if coalesce(v_format.rider_config, '{}'::jsonb) = '{}'::jsonb
     or jsonb_typeof(v_format.rider_config -> 'integrantes') <> 'array'
     or jsonb_array_length(v_format.rider_config -> 'integrantes') = 0 then
    raise exception
      'Configura primero el rider técnico de este Formato.';
  end if;

  select coalesce(max(r.version), 0) + 1
  into v_next_version
  from public.riders_tecnicos r
  where r.cotizacion_id = new.cotizacion_id;

  new.version := v_next_version;

  v_quote_number := regexp_replace(
    coalesce(
      nullif(trim(v_quote.numero::text), ''),
      v_quote.id::text
    ),
    '[^A-Za-z0-9_-]+',
    '-',
    'g'
  );

  new.numero :=
    'RDR-' || v_quote_number || '-V' || new.version::text;

  if new.generado_por is null then
    new.generado_por := auth.uid();
  end if;

  if new.generado_por is distinct from auth.uid() then
    raise exception
      'El usuario que genera el rider no coincide con la sesión activa.';
  end if;

  new.created_at := coalesce(new.created_at, now());
  new.updated_at := now();

  return new;
end;
$$;

drop trigger if exists riders_tecnicos_prepare_row
  on public.riders_tecnicos;

create trigger riders_tecnicos_prepare_row
before insert or update
on public.riders_tecnicos
for each row
execute function public.prepare_technical_rider_row();


-- ------------------------------------------------------------
-- 4. RLS
-- ------------------------------------------------------------

alter table public.riders_tecnicos
  enable row level security;

drop policy if exists riders_tecnicos_select_miembro
  on public.riders_tecnicos;

create policy riders_tecnicos_select_miembro
on public.riders_tecnicos
for select
to authenticated
using (
  public.is_workspace_member(workspace_id)
);

drop policy if exists riders_tecnicos_insert_miembro
  on public.riders_tecnicos;

create policy riders_tecnicos_insert_miembro
on public.riders_tecnicos
for insert
to authenticated
with check (
  public.is_workspace_member(workspace_id)
  and generado_por = auth.uid()
);

drop policy if exists riders_tecnicos_update_miembro
  on public.riders_tecnicos;

create policy riders_tecnicos_update_miembro
on public.riders_tecnicos
for update
to authenticated
using (
  public.is_workspace_member(workspace_id)
)
with check (
  public.is_workspace_member(workspace_id)
);

drop policy if exists riders_tecnicos_delete_owner
  on public.riders_tecnicos;

create policy riders_tecnicos_delete_owner
on public.riders_tecnicos
for delete
to authenticated
using (
  public.is_workspace_owner(workspace_id)
);


-- ------------------------------------------------------------
-- 5. STORAGE PRIVADO PARA RIDERS
-- ------------------------------------------------------------

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'riders-pdf',
  'riders-pdf',
  false,
  10485760,
  array['application/pdf']
)
on conflict (id)
do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists riders_pdf_select_miembro
  on storage.objects;

create policy riders_pdf_select_miembro
on storage.objects
for select
to authenticated
using (
  bucket_id = 'riders-pdf'
  and (storage.foldername(name))[1] = 'workspace'
  and coalesce((storage.foldername(name))[2], '') ~ '^[0-9]+$'
  and public.is_workspace_member(
    ((storage.foldername(name))[2])::bigint
  )
);

drop policy if exists riders_pdf_insert_miembro
  on storage.objects;

create policy riders_pdf_insert_miembro
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'riders-pdf'
  and (storage.foldername(name))[1] = 'workspace'
  and coalesce((storage.foldername(name))[2], '') ~ '^[0-9]+$'
  and public.is_workspace_member(
    ((storage.foldername(name))[2])::bigint
  )
);

drop policy if exists riders_pdf_update_miembro
  on storage.objects;

create policy riders_pdf_update_miembro
on storage.objects
for update
to authenticated
using (
  bucket_id = 'riders-pdf'
  and (storage.foldername(name))[1] = 'workspace'
  and coalesce((storage.foldername(name))[2], '') ~ '^[0-9]+$'
  and public.is_workspace_member(
    ((storage.foldername(name))[2])::bigint
  )
)
with check (
  bucket_id = 'riders-pdf'
  and (storage.foldername(name))[1] = 'workspace'
  and coalesce((storage.foldername(name))[2], '') ~ '^[0-9]+$'
  and public.is_workspace_member(
    ((storage.foldername(name))[2])::bigint
  )
);

drop policy if exists riders_pdf_delete_owner
  on storage.objects;

create policy riders_pdf_delete_owner
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'riders-pdf'
  and (storage.foldername(name))[1] = 'workspace'
  and coalesce((storage.foldername(name))[2], '') ~ '^[0-9]+$'
  and public.is_workspace_owner(
    ((storage.foldername(name))[2])::bigint
  )
);


-- ------------------------------------------------------------
-- 6. PERMISOS
-- ------------------------------------------------------------

grant select, insert, update, delete
on public.riders_tecnicos
to authenticated;

grant usage, select
on sequence public.riders_tecnicos_id_seq
to authenticated;

comment on table public.riders_tecnicos is
  'Riders técnicos congelados y versionados, generados desde cotizaciones confirmadas o aprobadas.';

comment on column public.riders_tecnicos.datos_snapshot is
  'Fotografía permanente del evento, Artista, Formato, integrantes, canales, monitores, backline y requisitos técnicos.';

commit;


-- ============================================================
-- VERIFICACIÓN
-- ============================================================

select
  column_name,
  data_type
from information_schema.columns
where table_schema = 'public'
  and table_name = 'riders_tecnicos'
order by ordinal_position;

select
  id,
  public,
  file_size_limit,
  allowed_mime_types
from storage.buckets
where id = 'riders-pdf';
